package com.Pages.Main;

import com.Pages.AskQuestionPage.StocksQuestionPage;
import com.Support.Constant;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DNartey
 */
public class NoUseMain extends javax.swing.JFrame {

    /**
     * Creates new form NoUseMain
     */
    public NoUseMain() {
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholePanel = new javax.swing.JPanel();
        questionPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        YEsBtn = new javax.swing.JButton();
        NoBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wholePanel.setBackground(new java.awt.Color(240, 235, 216));
        wholePanel.setPreferredSize(new java.awt.Dimension(637, 583));
        wholePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionPanel.setBackground(new java.awt.Color(240, 235, 216));
        questionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        wholePanel.add(questionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        headerPanel.setBackground(new java.awt.Color(34, 47, 66));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pSsmallLogo.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wholePanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        jLabel2.setBackground(new java.awt.Color(34, 47, 66));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 64, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Or \"No\" to start again.");
        wholePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 440, -1));

        YEsBtn.setBackground(new java.awt.Color(34, 47, 66));
        YEsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YEsBtn.setForeground(new java.awt.Color(255, 255, 255));
        YEsBtn.setText("Yes");
        YEsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YEsBtnActionPerformed(evt);
            }
        });
        wholePanel.add(YEsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, -1));

        NoBtn2.setBackground(new java.awt.Color(34, 47, 66));
        NoBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoBtn2.setForeground(new java.awt.Color(255, 255, 255));
        NoBtn2.setText("No");
        NoBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtn2ActionPerformed(evt);
            }
        });
        wholePanel.add(NoBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        jLabel3.setBackground(new java.awt.Color(34, 47, 66));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 64, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("You currently have no use for PennySaver");
        wholePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, -1));

        jLabel4.setBackground(new java.awt.Color(34, 47, 66));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 64, 76));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Click \"Yes\" to log out and delete account");
        wholePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void YEsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YEsBtnActionPerformed
        Constant.DoConnect();
        String[] options={"Yes", "No"};
        int f =  JOptionPane.showOptionDialog(null, "Are You Delete Your Account?", "Confirm Save", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(f==JOptionPane.YES_OPTION){
            try{
                //String sql = "DELETE FROM ROOT.PUSERS WHERE USERNAME = 'bb123' AND PASSWORD = 'VGVzdCQxMjM=' AND FIRSTNAME = 'Betty' AND LASTNAME = 'Beryl' AND EMAILADDRESS = 'bb@gmail.com' AND NET_WORTH = 9000000.0 AND NET_INCOME = 7000.0 AND MONTHLY_SAVINGS = 3000.0 AND EMPLOYMENT_STATUS = 'Self-Employed';\n";
                String sql = "DELETE FROM ROOT.PUSERS WHERE USERNAME = ?";
                PreparedStatement statement = Constant.con.prepareStatement(sql);
                statement.setString(1, Constant.currentUser);
                int rowsInserted = statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Goodbye, Please come again");
                System.exit(0);
            }catch(Exception e){
                        
                    }
                }
    }//GEN-LAST:event_YEsBtnActionPerformed

    private void NoBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtn2ActionPerformed
        StocksQuestionPage m = new StocksQuestionPage();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_NoBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoUseMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoUseMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoUseMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoUseMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoUseMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoBtn2;
    private javax.swing.JButton YEsBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JPanel wholePanel;
    // End of variables declaration//GEN-END:variables
}
