package com;

/**
 *
 * @author DNartey
 */
public class EditPersonalInfoPage extends javax.swing.JFrame {

    /**
     * Creates new form EditInfoPage
     */
    public EditPersonalInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPersonalInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPersonalInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPersonalInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPersonalInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPersonalInfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JButton Edit3;
    private javax.swing.JButton Edit4;
    private javax.swing.JTextField autoAndCommutingField;
    private javax.swing.JTextField autoAndCommutingField1;
    private javax.swing.JTextField autoAndCommutingField2;
    private javax.swing.JTextField autoAndCommutingField3;
    private javax.swing.JTextField autoAndCommutingField4;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn4;
    private javax.swing.JTextField billsAndUtilitiesField;
    private javax.swing.JTextField billsAndUtilitiesField1;
    private javax.swing.JTextField billsAndUtilitiesField2;
    private javax.swing.JTextField billsAndUtilitiesField3;
    private javax.swing.JTextField billsAndUtilitiesField4;
    private javax.swing.JTextField diningAndDrinksField;
    private javax.swing.JTextField diningAndDrinksField1;
    private javax.swing.JTextField diningAndDrinksField2;
    private javax.swing.JTextField diningAndDrinksField3;
    private javax.swing.JTextField diningAndDrinksField4;
    private javax.swing.JTextField educationField;
    private javax.swing.JTextField educationField1;
    private javax.swing.JTextField educationField2;
    private javax.swing.JTextField educationField3;
    private javax.swing.JTextField educationField4;
    private javax.swing.JTextField entertainmentField;
    private javax.swing.JTextField entertainmentField1;
    private javax.swing.JTextField entertainmentField2;
    private javax.swing.JTextField entertainmentField3;
    private javax.swing.JTextField entertainmentField4;
    private javax.swing.JTextField feesField;
    private javax.swing.JTextField feesField1;
    private javax.swing.JTextField feesField2;
    private javax.swing.JTextField feesField3;
    private javax.swing.JTextField feesField4;
    private javax.swing.JTextField homeField;
    private javax.swing.JTextField homeField1;
    private javax.swing.JTextField homeField2;
    private javax.swing.JTextField homeField3;
    private javax.swing.JTextField homeField4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loansField;
    private javax.swing.JTextField loansField1;
    private javax.swing.JTextField loansField2;
    private javax.swing.JTextField loansField3;
    private javax.swing.JTextField loansField4;
    private javax.swing.JPanel myChartPanel;
    private javax.swing.JPanel myChartPanel1;
    private javax.swing.JPanel myChartPanel2;
    private javax.swing.JPanel myChartPanel3;
    private javax.swing.JPanel myChartPanel4;
    private javax.swing.JTextField otherField;
    private javax.swing.JTextField otherField1;
    private javax.swing.JTextField otherField2;
    private javax.swing.JTextField otherField3;
    private javax.swing.JTextField otherField4;
    private javax.swing.JTextField personalCareField;
    private javax.swing.JTextField personalCareField1;
    private javax.swing.JTextField personalCareField2;
    private javax.swing.JTextField personalCareField3;
    private javax.swing.JTextField personalCareField4;
    private javax.swing.JTextField shoppingField;
    private javax.swing.JTextField shoppingField1;
    private javax.swing.JTextField shoppingField2;
    private javax.swing.JTextField shoppingField3;
    private javax.swing.JTextField shoppingField4;
    private javax.swing.JTextField travelField;
    private javax.swing.JTextField travelField1;
    private javax.swing.JTextField travelField2;
    private javax.swing.JTextField travelField3;
    private javax.swing.JTextField travelField4;
    // End of variables declaration//GEN-END:variables
}
